### ISSUE TITLE
Include upstream dependencies in the source tree?

### ISSUE THREAD

**Issue by rdipardo** [ThosRTanner/Docking_Dialogue_Interface#1]
*In reply to [this forum posting](https://community.notepad-plus-plus.org/post/91371).*

---

This project does not build unless the source tree of Don Ho's [plugin template](https://github.com/npp-plugins/plugintemplate) has been copied into the `plugintemplate/` path.

Assuming the template source needs no modification, the easiest solution would be a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

At the root of the project, execute

    git submodule add https://github.com/npp-plugins/plugintemplate.git
    
Then commit the resulting changes, e.g.,

~~~diff
diff --git a/.gitmodules b/.gitmodules
new file mode 100644
index 0000000..7144c75
--- /dev/null
+++ b/.gitmodules
@@ -0,0 +1,3 @@
+[submodule "plugintemplate"]
+       path = plugintemplate
+       url = https://github.com/npp-plugins/plugintemplate
diff --git a/plugintemplate b/plugintemplate
new file mode 160000
index 0000000..fd051e4
--- /dev/null
+++ b/plugintemplate
@@ -0,0 +1 @@
+Subproject commit fd051e4cadaa2adcbedfdc27a817bc72eb0ae174
~~~

Users of the project only have to remember the extra `--recursive` switch when they clone (Visual Studio's ["Clone a repo"](https://learn.microsoft.com/en-us/visualstudio/version-control/git-clone-repository) feature should do this automatically), or else they can run `git submodule update --init` at any time afterward.

**Comment by ThosRTanner** [comment]
I'm always slightly worried about submodules because you can accidentally change them. I've been updating the documentation mainly (and fiddling around with the implementation). But will have another look at submodules 

Appreciate the feedback
